local ox = require 'ox'
local PORT = 8092 or ...
print(PORT)
ox.split(1,function()
  print(ox.tcpserv(PORT, function(c)
    return ox.readln(c, 2048, function(c, line)
      return ox.write(c, line..'\n', function(c)
        ox.close(c)
        ox.stop()
      end)
    end)
  end))
  ox.start()
end)

local function handleconn(c)
  return ox.write(c, 'Hello\n', function(c)
    return ox.readln(c, 2048, function(c, line)
      print('connection readln', line)
      assert(line=='Hello')
      ox.close(c)
      ox.stop()
    end)
  end)
end

ox.at(ox.time+1, function()
  print(ox.tcpconn('::1',PORT,handleconn))
end)
ox.start()
